#!/usr/bin/env python3
"""
generate_typesupport_map.py

Scans the idl/ directory for OpenDDS IDL files named "${IDL_NAME}.idl"
(by convention these end in "Data.idl", e.g. "TrackJoinData.idl") and
generates a "generated.hpp" file containing a lookup map from type name
to a FactoryItem holding:
  - createTypeSupport: builds the DDS::TypeSupport_var for the type
  - bindWriter: narrows a generic DDS::DataWriter_ptr to the typed writer
                and returns a closure that writes an opaque sample

For each discovered IDL file, IDL_NAME is the file's stem (filename minus
the .idl extension), and it is substituted into the include path, the map
key, and every namespace-qualified type reference for that entry.
"""

import os
import sys
import glob

IDL_DIR = "idl"
OUTPUT_FILE = "src/generated.hpp"

HEADER_TOP = """#pragma once
#include <unordered_map>
#include <string>
#include <functional>
#include <dds/DCPS/JsonValueWriter.h>
%%INCLUDES%%
// This file is auto-generated by generate_typesupport_map.py. Do not edit by hand.
struct FactoryItem {
    std::function<DDS::TypeSupport_var()> createTypeSupport;
    std::function<std::function<bool(const void*)>(DDS::DataWriter_ptr)> bindWriter;
    std::function<std::function<bool(const char*)>(DDS::DataWriter_ptr)> bindStringWriter;
    std::function<std::function<std::string()>(DDS::DataWriter_ptr)> bindGenerator;
    // std::function<std::function<bool(const void*)>(DDS::DataWriter_ptr)> bindReader;
};
std::unordered_map<std::string, FactoryItem> typeSupportFactory = {
%%ENTRIES%%
};
"""

INCLUDE_TEMPLATE = '#include "{idl_name}TypeSupportImpl.h"'

ENTRY_TEMPLATE = """    {{ "{idl_name}_Message", {{
        []() -> DDS::TypeSupport_var {{ return new {idl_name}::MessageTypeSupportImpl(); }},
        [](DDS::DataWriter_ptr dw) -> std::function<bool(const void*)> {{
            {idl_name}::MessageDataWriter_var writer = {idl_name}::MessageDataWriter::_narrow(dw);
            return [writer](const void* sample) -> bool {{
                const {idl_name}::Message* msg = static_cast<const {idl_name}::Message*>(sample);
                return writer->write(*msg, DDS::HANDLE_NIL) == DDS::RETCODE_OK;
            }};
        }},
        [](DDS::DataWriter_ptr dw) -> std::function<bool(const char*)> {{
            {idl_name}::MessageDataWriter_var writer = {idl_name}::MessageDataWriter::_narrow(dw);
            auto mts = new {idl_name}::MessageTypeSupportImpl();
            return [writer, mts](const char* s) -> bool {{
                {idl_name}::Message msg;
                auto format = mts->make_format(OpenDDS::DCPS::JSON_DATA_REPRESENTATION);
                if (mts->decode_from_string(s, msg, format) != DDS::RETCODE_OK) {{
                    std::cerr << "Failed to decode" << std::endl;
                    return false;
                }} 
                std::cout << "Success" << std::endl;
                return writer->write(msg, DDS::HANDLE_NIL) == DDS::RETCODE_OK;
            }};
        }},
        [](DDS::DataWriter_ptr dw) -> std::function<std::string()> {{
            {idl_name}::MessageDataWriter_var writer = {idl_name}::MessageDataWriter::_narrow(dw);
            auto mts = new {idl_name}::MessageTypeSupportImpl();
            return [writer, mts]() -> std::string {{
                {idl_name}::Message msg;
                const static std::string s = "";
                auto format = mts->make_format(OpenDDS::DCPS::JSON_DATA_REPRESENTATION);
                if (mts->decode_from_string(s.c_str(), msg, format) != DDS::RETCODE_OK) {{
                    assert(0 && "Unreachable");
                }} 
                return OpenDDS::DCPS::to_json(msg);
            }};
        }}
    }}}},"""


def discover_idl_names(idl_dir):
    """Return a sorted list of IDL_NAMEs found in idl_dir, one per *.idl file."""
    if not os.path.isdir(idl_dir):
        print(f"error: idl directory '{idl_dir}' not found", file=sys.stderr)
        sys.exit(1)

    idl_files = sorted(glob.glob(os.path.join(idl_dir, "*.idl")))
    if not idl_files:
        print(f"warning: no .idl files found in '{idl_dir}'", file=sys.stderr)

    idl_names = []
    for path in idl_files:
        filename = os.path.basename(path)
        idl_name, _ext = os.path.splitext(filename)
        idl_names.append(idl_name)

    return idl_names


def render(idl_names):
    includes = "\n".join(INCLUDE_TEMPLATE.format(idl_name=name) for name in idl_names)
    entries = "\n".join(ENTRY_TEMPLATE.format(idl_name=name) for name in idl_names)
    return HEADER_TOP.replace("%%INCLUDES%%", includes).replace("%%ENTRIES%%", entries)


def main():
    idl_names = discover_idl_names(IDL_DIR)
    content = render(idl_names)

    with open(OUTPUT_FILE, "w") as f:
        f.write(content)

    print(f"Generated {OUTPUT_FILE} with {len(idl_names)} type support entr"
          f"{'y' if len(idl_names) == 1 else 'ies'}: {', '.join(idl_names) or '(none)'}")


if __name__ == "__main__":
    main()
